# note: used in the context of image promotion pipeline only!
osp_release: "{{ dci_topic | regex_replace('OSP(\\d\\d)$', 'rhos-\\1') }}"
containerized_overcloud: false
#docker_registry_host: registry.distributed-ci.io
#docker_registry_namespace: "{{ dci_topic | regex_replace('OSP(\\d\\d)$', 'rhosp\\1') }}"
undercloud_image_url: '{{ dci_baseurl }}/rhel-guest-image.x86_64.qcow2'
overcloud_image_url: file:///usr/share/rhosp-director-images/overcloud-full.tar
ipa_image_url: file:///usr/share/rhosp-director-images/ironic-python-agent.tar

mtu: 1350
mtu_interface:
  - eth0
  - eth1
  - eth2

images:
    - name: rhel
      url: "{{ undercloud_image_url }}"
      type: qcow2
      md5sum: "0bfff47b55a9428c83d2235da9d470de  rhel-guest-image.x86_64.qcow2"
    - name: overcloud-full
      url: "{{ overcloud_image_url }}"
      type: tar
    - name: ipa_images
      url: "{{ ipa_image_url }}"
      type: tar

inject_images:
    - "ironic-python-agent.initramfs"
    - "ironic-python-agent.kernel"
    - "overcloud-full.qcow2"
    - "overcloud-full.initrd"
    - "overcloud-full.vmlinuz"
repos:
  - type: file
    filename: dci_repo.repo
    down_url: '{{ dci_baseurl }}/dci_repo/dci_repo.repo'

use_rhsm: true
# Reuse the local system pool id by default
pool_id: "{{ lookup('pipe','sudo subscription-manager list --consumed --pool-only') }}"
rhsm_username: "{{ rhsm_login }}"
rhsm_password: "{{ rhsm_password }}"
rhsm_repos:
  - name: rhel-{{ rhel_version_number }}-server-rpms
  - name: rhel-{{ rhel_version_number }}-server-extras-rpms
  - name: rhel-{{ rhel_version_number }}-server-rh-common-rpms
  - name: rhel-{{ rhel_version_number }}-server-cert-rpms

repo_cmd_before: |
  subscription-manager remove --all || true
  subscription-manager unregister || true
  rm -Rf /etc/yum.repos.d/*.repo
repo_cmd_after: |
  rm -Rf /etc/yum.repos.d/delorean*
  yum repolist
  yum clean all
  if [[ $(hostname) =~ 'undercloud' ]]; then
    yum -y remove rhosp-director-images.noarch
    yum -y install rhosp-director-images.noarch
    md5sum /usr/share/rhosp-director-images/overcloud-full.tar > /usr/share/rhosp-director-images/overcloud-full.tar.md5
    md5sum /usr/share/rhosp-director-images/ironic-python-agent.tar > /usr/share/rhosp-director-images/ironic-python-agent.tar.md5
  fi

undercloud_ip_retries: 30
enable_vbmc: true
undercloud_setup: true
virthost_repo_setup: true
baseos_as_undercloud: true
use_external_images: true
download_overcloud_images: false
ovb_setup_connectivity: true
non_root_user_setup: true
package_installs: true
hostname_correction: true
selinux_enforcing: true
step_introspect: false
validate_ipmi_step: false
